apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: sns
data:
  config.json: |
    {
      "server_port": 3000,
      "redis_host": "sns-redis-master",
      "redis_port": 6379
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: sns
  labels:
    app: payment
spec:
  selector:
    matchLabels:
      app: payment
  replicas: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: payment
        image: sns-payment:latest
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        ports:
        - containerPort: 3000
        env:
          - name: NODE_ENV
            value: "production"
          - name: CONFIG_DIR
            value: "/opt/sns/config"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-conf
                key: redis_password
        imagePullPolicy: "Never"
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /probes/liveness
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /probes/readiness
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 30
        volumeMounts:
        - name: payment-config
          mountPath: "/opt/sns/config"
      serviceAccountName: sns-sa
      volumes:
      - name: payment-config
        configMap:
          name: payment-config
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: sns
  labels:
    app: payment
    layer: api
spec:
  ports:
  - port: 3000
    targetPort: 3000
    name: web
  selector:
    app: payment
